version: '3.7'
services:
  server:
    build:
      context: ./
      dockerfile: backend/Dockerfile
    image: nodejs
    container_name: node-js-con
    command: node ./src/index.js
    volumes:
      - ./server/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "4001:8080"
    depends_on:
      - mongo
    env_file: ./.env
    networks:
      - app-network
  mongo:
    image: mongo
    volumes:
      - data-volume:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network
networks:
    app-network:
        driver: bridge
volumes:
    data-volume:
    node_modules:
    web-root:
      driver: local